openapi: 3.0.0
info:
  title: Bloggers API
  version: 1.0.0
  description: Bloggers API documentation

tags:
  - name: Auth
    description: API for managing authentication and authorization
  - name: Blogs
    description: API for managing blogs
  - name: Posts
    description: API for managing posts
  - name: Comments
    description: API for managing comments
  - name: SecurityDevices
    description: API for managing security devices
  - name: Users
    description: API for managing users
  - name: Testing
    description: API for clearing the database